/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crimemanagement;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author mmath
 */
public class CaseFormGUI extends javax.swing.JFrame {
    Connection conn = DBConnection.connect();


    /**
     * Creates new form CaseFormGUI
     */
    public CaseFormGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDetails = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        cmbOfficer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CASE  -  MANAGEMENT");

        jLabel2.setText("CASE DETAILS :");

        txtDetails.setText("ENTER CASE DETAILS :");
        txtDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailsActionPerformed(evt);
            }
        });

        jLabel3.setText("ATTENDING OFFICER :");

        jLabel4.setText("CATEGORY :");

        txtCategory.setText("ENTER THE CATEGORY :");

        jLabel5.setText("LOCATION");

        txtLocation.setText("ENTER THE LOCATION");
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        jLabel6.setText("STATUS : ");

        txtStatus.setText("ENTER CASE STATUS");

        jLabel7.setText("ADD CASE: ");

        btnAdd.setText("ADD CASE ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel8.setText("UPDATE CASE :");

        btnUpdate.setText("UPDATE CASE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel9.setText("DELETE CASE : ");

        btnDelete.setText("DELETE CASE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmbOfficer.setEditable(true);
        cmbOfficer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOfficerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDetails)
                    .addComponent(txtCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtLocation)
                    .addComponent(txtStatus)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbOfficer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbOfficer, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailsActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    
    
    
    
    //DELETE BUTTON
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       try {
           // Ask for Case ID
             String id = JOptionPane.showInputDialog(this, "Enter Case ID to delete:");

            if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Case ID.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

         // Confirm before deleting
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete Case ID " + id + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
           return; // user clicked No
        }

             // SQL delete query
            String sql = "DELETE FROM `case` WHERE `CaseID`=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(id));

            int rows = ps.executeUpdate();

            if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Case deleted successfully!");
            } else {
            JOptionPane.showMessageDialog(this, "No case found with ID " + id, "Not Found", JOptionPane.WARNING_MESSAGE);
            }

            } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(this, "Invalid Case ID. Please enter a number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException e) {
                 JOptionPane.showMessageDialog(this, "Error deleting case: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    
    
    // ADD CASE BUTTON
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       try {
    // Get the selected or entered officer name
    String officerName = ((String) cmbOfficer.getSelectedItem()).trim();

    if (officerName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter or select an attending officer name.");
        return;
    }

    // Split name into first and last 
    String[] parts = officerName.split(" ", 2);
    String firstName = parts[0];
    String lastName = (parts.length > 1) ? parts[1] : "";

    int officerID = -1;

    // Check if officer already exists
    String findID = "SELECT OfficerID FROM officer WHERE FirstName = ? AND LastName = ?";
    PreparedStatement findPS = conn.prepareStatement(findID);
    findPS.setString(1, firstName);
    findPS.setString(2, lastName);
    ResultSet rs = findPS.executeQuery();

    if (rs.next()) {
        officerID = rs.getInt("OfficerID"); // officer already exists
    } else {
        //Add a new officer automatically
        String insertOfficer = "INSERT INTO officer (FirstName, LastName, `Rank`, Phone) VALUES (?, ?, 'Unknown', 'N/A')";
        PreparedStatement insertPS = conn.prepareStatement(insertOfficer, Statement.RETURN_GENERATED_KEYS);
        insertPS.setString(1, firstName);
        insertPS.setString(2, lastName);
        insertPS.executeUpdate();

        // Get the new OfficerID
        ResultSet generatedKeys = insertPS.getGeneratedKeys();
        if (generatedKeys.next()) {
            officerID = generatedKeys.getInt(1);
        }
    }

    //Insert new case with that OfficerID
    String sql = "INSERT INTO `case` (`CaseDetails`, `AttendingOfficer`, `Category`, `Location`, `ReportedOn`, `Status`) VALUES (?, ?, ?, ?, CURDATE(), ?)";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setString(1, txtDetails.getText().trim());
    ps.setInt(2, officerID);
    ps.setString(3, txtCategory.getText().trim());
    ps.setString(4, txtLocation.getText().trim());
    ps.setString(5, txtStatus.getText().trim());
    ps.executeUpdate();

    JOptionPane.showMessageDialog(this, "Case added successfully!");

    // Clear all fields and refresh officer list
    txtDetails.setText("");
    txtCategory.setText("");
    txtLocation.setText("");
    txtStatus.setText("");
    loadOfficerNames(); // reload combo box with updated list
    cmbOfficer.setSelectedIndex(-1);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error adding case: " + e.getMessage());
}

    }//GEN-LAST:event_btnAddActionPerformed

    
    
    
    //UPDATE THE CASE BUTTON
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
    // Ask for the Case ID to update
    String id = JOptionPane.showInputDialog(this, "Enter Case ID to update:");

    if (id == null || id.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a valid Case ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get officer name from combo box
    String officerName = ((String) cmbOfficer.getSelectedItem()).trim();

    if (officerName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select or type the attending officer name.");
        return;
    }

    // Split the name into first and last (simple split)
    String[] parts = officerName.split(" ", 2);
    String firstName = parts[0];
    String lastName = (parts.length > 1) ? parts[1] : "";

    int officerID = -1;

    //Try to find this officer in the database
    String findID = "SELECT OfficerID FROM officer WHERE FirstName = ? AND LastName = ?";
    PreparedStatement findPS = conn.prepareStatement(findID);
    findPS.setString(1, firstName);
    findPS.setString(2, lastName);
    ResultSet rs = findPS.executeQuery();

    if (rs.next()) {
        officerID = rs.getInt("OfficerID");
    } else {
        //If not found, add a new officer automatically
        String insertOfficer = "INSERT INTO officer (FirstName, LastName, `Rank`, Phone) VALUES (?, ?, 'Unknown', 'N/A')";
        PreparedStatement insertPS = conn.prepareStatement(insertOfficer, Statement.RETURN_GENERATED_KEYS);
        insertPS.setString(1, firstName);
        insertPS.setString(2, lastName);
        insertPS.executeUpdate();

        ResultSet generatedKeys = insertPS.getGeneratedKeys();
        if (generatedKeys.next()) {
            officerID = generatedKeys.getInt(1);
        }
    }

    // Update the case record with the correct OfficerID
    String sql = "UPDATE `case` SET `CaseDetails`=?, `AttendingOfficer`=?, `Category`=?, `Location`=?, `Status`=? WHERE `CaseID`=?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setString(1, txtDetails.getText().trim());
    ps.setInt(2, officerID);
    ps.setString(3, txtCategory.getText().trim());
    ps.setString(4, txtLocation.getText().trim());
    ps.setString(5, txtStatus.getText().trim());
    ps.setInt(6, Integer.parseInt(id));

    int rows = ps.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(this, "Case updated successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "No case found with ID " + id, "Not Found", JOptionPane.WARNING_MESSAGE);
    }

    // Clear fields and refresh combo box
    txtDetails.setText("");
    txtCategory.setText("");
    txtLocation.setText("");
    txtStatus.setText("");
    loadOfficerNames();
    cmbOfficer.setSelectedIndex(-1);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Please enter a valid numeric Case ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error updating case: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
}

       
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    
    private void cmbOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOfficerActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseFormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbOfficer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void loadOfficerNames() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
